/**
 * Colorado community corrections programs — the state's halfway houses.
 * Generated by scripts/ingest/commcorr.mjs; regenerate with `npm run ingest`.
 *
 * Source: Colorado Division of Criminal Justice, Office of Community
 * Corrections. Scraped, because DCJ publishes no API and no export.
 *
 * This is kept apart from the SAMHSA `Resource` type on purpose. A treatment
 * facility answers "can I get help here"; a halfway house answers "will they
 * take me", and that question has its own vocabulary — judicial district,
 * population served, and which of the three specialised treatment tracks the
 * bed sits on. Flattening the two loses exactly the fields that decide a
 * placement.
 */

import raw from './commcorr.generated.json';

/** The three specialised tracks DCJ runs inside community corrections. */
export type TrackName = 'IRT' | 'SOSTCC' | 'RDDT' | (string & {});

export const TRACK_LABELS: Record<string, { short: string; long: string }> = {
  IRT: { short: 'Intensive residential', long: 'Intensive Residential Treatment' },
  SOSTCC: { short: 'Sex-offence treatment', long: 'Sex Offender Supervision and Treatment' },
  RDDT: { short: 'Dual diagnosis', long: 'Residential Dual Diagnosis Treatment' },
};

export type Track = {
  track: TrackName;
  length: string | null;
  substanceAbuse: string | null;
  mentalHealth: string | null;
  medical: string | null;
  sexOffenders: string | null;
  violentOffenders: string | null;
  notes: string | null;
};

export type CommCorrFlags = {
  justiceInvolved: boolean;
  men: boolean;
  women: boolean;
  acceptsSexOffense: boolean;
  acceptsViolentOffense: boolean;
  dualDiagnosis: boolean;
  residentialTreatment: boolean;
};

export type CommCorrProgram = {
  id: string;
  source: 'dcj';
  kinds: string[];
  name: string;
  /** The judicial district the program is filed under. */
  subtitle: string | null;
  address: string | null;
  city: string | null;
  state: string;
  zip: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  director: string | null;
  lat: number | null;
  lng: number | null;
  flags: CommCorrFlags;
  tracks: Track[];
  populationServed: string | null;
};

type Payload = {
  source: string;
  sourceUrl: string;
  fetchedAt: string;
  state: string;
  count: number;
  resources: CommCorrProgram[];
};

const payload = raw as unknown as Payload;

export const PROGRAMS: CommCorrProgram[] = payload.resources;
export const COMMCORR_FETCHED_AT = payload.fetchedAt;
export const COMMCORR_SOURCE = payload.source;
export const COMMCORR_SOURCE_URL = payload.sourceUrl;

export type CommCorrFilter = 'women' | 'men' | 'dualDiagnosis' | 'residentialTreatment' | 'acceptsSexOffense';

export function applyCommCorrFilters(
  list: CommCorrProgram[],
  active: CommCorrFilter[],
): CommCorrProgram[] {
  if (active.length === 0) return list;
  return list.filter((p) => active.every((f) => p.flags[f]));
}

export function searchPrograms(list: CommCorrProgram[], query: string): CommCorrProgram[] {
  const q = query.trim().toLowerCase();
  if (!q) return list;
  return list.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      (p.city ?? '').toLowerCase().includes(q) ||
      (p.zip ?? '').includes(q) ||
      (p.subtitle ?? '').toLowerCase().includes(q),
  );
}

/** Judicial district number, for grouping. `null` when it cannot be read. */
export function districtNumber(p: CommCorrProgram): number | null {
  const n = /^(\d+)/.exec(p.subtitle ?? '');
  return n ? Number(n[1]) : null;
}
