/**
 * Colorado treatment facilities, generated by scripts/ingest/samhsa.mjs.
 *
 * Source: SAMHSA findtreatment.gov locator — US federal data, public domain.
 * Regenerate with `npm run ingest`.
 *
 * This is bundled rather than fetched for the same reason the hotlines are:
 * the app has to be useful with no signal. 276KB of JSON (24KB gzipped) is a
 * cheap price for a directory that works in a dead zone.
 */

import raw from './resources.generated.json';

export type ResourceFlags = {
  /** Runs programs for criminal justice / forensic clients. The single most
   *  important field in this dataset for a re-entry audience. */
  justiceInvolved: boolean;
  veterans: boolean;
  youngAdults: boolean;
  medicaid: boolean;
  medicare: boolean;
  slidingScale: boolean;
  freeOrNoPayment: boolean;
  spanish: boolean;
};

export type Resource = {
  id: string;
  source: string;
  /** 'sa' = substance use, 'mh' = mental health. Both when a facility does both. */
  kinds: string[];
  name: string;
  subtitle: string | null;
  address: string | null;
  city: string | null;
  state: string;
  zip: string | null;
  phone: string | null;
  website: string | null;
  lat: number | null;
  lng: number | null;
  flags: ResourceFlags;
  careTypes: string[];
  settings: string[];
  ageGroups: string[];
};

type Payload = {
  source: string;
  fetchedAt: string;
  state: string;
  count: number;
  resources: Resource[];
};

const payload = raw as unknown as Payload;

export const RESOURCES: Resource[] = payload.resources;
export const RESOURCES_FETCHED_AT = payload.fetchedAt;
export const RESOURCES_SOURCE = payload.source;

const isSubstance = (r: Resource) => r.careTypes.some((c) => /substance use/i.test(c));
const isMentalHealth = (r: Resource) => r.careTypes.some((c) => /mental health|serious mental/i.test(c));

/** Which bundled resources are worth showing for a given survey need. */
export function resourcesForNeed(needId: string): Resource[] {
  switch (needId) {
    case 'val_4': // Mental health services
      return RESOURCES.filter(isMentalHealth);
    case 'val_5': // Substance use treatment
      return RESOURCES.filter(isSubstance);
    case 'val_8': // Health care
      return RESOURCES;
    default:
      return [];
  }
}

/** Which bundled resources map onto one of the website's map categories. */
export function resourcesForCategory(slug: string): Resource[] {
  switch (slug) {
    case 'crisis-walk-in-centers':
      return RESOURCES.filter(
        (r) => isMentalHealth(r) && r.settings.some((s) => /24|crisis|emergency|hospital/i.test(s)),
      );
    case 'ua-sites':
      // Not urinalysis sites as such, but facilities that do testing and take
      // justice-involved clients are the closest honest match in this dataset.
      return RESOURCES.filter((r) => r.flags.justiceInvolved && isSubstance(r));
    default:
      return [];
  }
}

export type ResourceFilter = keyof ResourceFlags;

export function applyFilters(list: Resource[], active: ResourceFilter[]): Resource[] {
  if (active.length === 0) return list;
  return list.filter((r) => active.every((f) => r.flags[f]));
}

export function searchResources(list: Resource[], query: string): Resource[] {
  const q = query.trim().toLowerCase();
  if (!q) return list;
  return list.filter(
    (r) =>
      r.name.toLowerCase().includes(q) ||
      (r.city ?? '').toLowerCase().includes(q) ||
      (r.zip ?? '').includes(q),
  );
}
